### ISSUE TITLE
kano-wifi fails when using non-standard wifi dongle

### ISSUE THREAD

**Issue by rrgomez** [KanoComputing/kano-settings#351]
When using a non-standard (but completely supported) wifi dongle, kano-wifi bombs out with the following:

Traceback (most recent call last):
  File "/usr/bin/kano-wifi", line 358, in <module>
    iwl = IWList(wiface).getList(unsecure=False, first=False)
  File "/usr/lib/python2.7/dist-packages/kano/network.py", line 44, in __init__
    self.refresh(iwlist=iwlist)
  File "/usr/lib/python2.7/dist-packages/kano/network.py", line 209, in refresh
    self.data = parseRawData(rawdata)
  File "/usr/lib/python2.7/dist-packages/kano/network.py", line 88, in parseRawData
    cellNumber, cellData = parseCellData("\n".join(s))
  File "/usr/lib/python2.7/dist-packages/kano/network.py", line 172, in parseCellData
    cellData["Channel"] = getCellChannel(s)
  File "/usr/lib/python2.7/dist-packages/kano/network.py", line 121, in getCellChannel
    return s.strip().split(" ")[3][0:-1]
IndexError: list index out of range

Please let me know what other information I can include to help debug.

**Comment by alex5imon** [comment]
Thanks for reporting @rrgomez :)

Which WiFi dongle are you using?

**Comment by rrgomez** [comment]
Sure thing, I haven't had a chance to start digging into the python else I'd be able to give more reasonable information.

The card itself is a Netgear [WNDA4100](http://www.netgear.com/home/products/networking/wifi-adapters/WNDA4100.aspx)

It has USBIDs: 
  0846:9012 and 148f:3573

Chipset:
  Ralink RT3573

On a 14.04 install, this card works 'out of the box', reference to kernel driver:
  https://wireless.wiki.kernel.org/en/users/drivers/rt2800usb

IDS first seen in kernel 3.12:
  https://wikidevi.com/wiki/Netgear_WNDA4100

**Comment by alex5imon** [comment]
Excellent! Thanks @rrgomez I'll now create a ticket for the team to address this issue :)
